'use client';

import { useState, useEffect, useCallback } from 'react';
import { SidebarTrigger } from './ui/sidebar.js';
import { getChatTitle, getChatTitleByWorkspace } from '../actions.js';

export function ChatHeader({ chatId, workspaceId }) {
  const [title, setTitle] = useState(null);

  const fetchTitle = useCallback(() => {
    const fetcher = workspaceId ? getChatTitleByWorkspace(workspaceId) : getChatTitle(chatId);
    fetcher
      .then((t) => {
        if (t && t !== 'New Chat') setTitle(t);
      })
      .catch(() => {});
  }, [chatId, workspaceId]);

  // Fetch on mount and whenever chats are updated (title generated by LLM)
  useEffect(() => {
    fetchTitle();
    const handler = () => fetchTitle();
    window.addEventListener('chatsupdated', handler);
    return () => window.removeEventListener('chatsupdated', handler);
  }, [fetchTitle]);

  return (
    <header className="sticky top-0 flex items-center gap-2 bg-background px-2 py-1.5 md:px-2 z-10">
      {/* Mobile-only: open sidebar sheet */}
      <div className="md:hidden">
        <SidebarTrigger />
      </div>
      <h1 className="text-base font-medium text-muted-foreground truncate">
        {title || '\u00A0'}
      </h1>
    </header>
  );
}
